# Export a portable Windows x64 release, test the exported executable, and zip the whole folder.
param([string]$Name = ('SpaceFleet-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '-Windows-x64'))
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\godot.ps1"
if ($Name -notmatch '^[A-Za-z0-9_-]+$') { throw 'Use a simple output folder name.' }
$sfTemplate = Join-Path $ProjectDir '.godot/export-templates/4.7.2-stable/windows_release_x86_64.exe'
Add-Type -AssemblyName System.IO.Compression.FileSystem
if (!(Test-Path -LiteralPath $sfTemplate)) {
    $sfTemplateCache = Split-Path -Parent $sfTemplate
    New-Item -ItemType Directory -Force -Path $sfTemplateCache | Out-Null
    $sfTemplateArchive = Join-Path $sfTemplateCache 'Godot_v4.7.2-stable_mono_export_templates.tpz'
    if (!(Test-Path -LiteralPath $sfTemplateArchive)) {
        Write-Output 'Downloading official Godot 4.7.2 .NET templates (1.2 GB, first export only).'
        Invoke-WebRequest -Uri 'https://github.com/godotengine/godot-builds/releases/download/4.7.2-stable/Godot_v4.7.2-stable_mono_export_templates.tpz' -OutFile $sfTemplateArchive
    }
    if ((Get-FileHash -LiteralPath $sfTemplateArchive -Algorithm SHA256).Hash.ToLowerInvariant() -ne '92f8681e349ef1f90891b792da95e3b2b0bd1ed610b78018c58feb2d87e15a9d') { throw 'Official template archive SHA-256 mismatch.' }
    $sfTemplateZip = [IO.Compression.ZipFile]::OpenRead($sfTemplateArchive)
    try {
        $sfEntry = $sfTemplateZip.GetEntry('templates/windows_release_x86_64.exe')
        if ($null -eq $sfEntry) { throw 'Windows x64 release template missing.' }
        [IO.Compression.ZipFileExtensions]::ExtractToFile($sfEntry,$sfTemplate,$false)
    } finally { $sfTemplateZip.Dispose() }
    # Only the one verified executable is needed after installation.
    Remove-Item -LiteralPath $sfTemplateArchive
}
$sfLicenseCache = Join-Path $ProjectDir '.godot/export-licenses'
New-Item -ItemType Directory -Force -Path $sfLicenseCache | Out-Null
foreach ($sfUpstreamNotice in @('LICENSE.txt','COPYRIGHT.txt')) {
    $sfNoticePath = Join-Path $sfLicenseCache "GODOT-$sfUpstreamNotice"
    if (!(Test-Path -LiteralPath $sfNoticePath)) {
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/godotengine/godot/4.7.2-stable/$sfUpstreamNotice" -OutFile $sfNoticePath
    }
}
$sfRoot = Join-Path $ProjectDir 'builds'
$sfOutput = Join-Path $sfRoot $Name
if (Test-Path -LiteralPath $sfOutput) { throw "Output already exists; choose another -Name: $sfOutput" }
$sfPreset = Join-Path $ProjectDir 'export_presets.cfg'
if ((Test-Path -LiteralPath $sfPreset) -and !(Get-Content -LiteralPath $sfPreset -Encoding UTF8 -Raw).StartsWith('; Generated by tools/export-windows.ps1.')) {
    throw 'Preserving an existing export_presets.cfg; use its export settings or back it up before running this helper.'
}
$sfConfig = (Get-Content (Join-Path $PSScriptRoot 'windows-export.cfg') -Encoding UTF8 -Raw).Replace('@WINDOWS_RELEASE_TEMPLATE@', ($sfTemplate -replace '\\','/'))
[IO.File]::WriteAllText($sfPreset, $sfConfig, [Text.UTF8Encoding]::new($false))
New-Item -ItemType Directory -Force -Path $sfOutput | Out-Null
New-Item -ItemType File -Force -Path (Join-Path $sfRoot '.gdignore') | Out-Null
$sfLogs = Join-Path $ProjectDir "shots/$Name"
New-Item -ItemType Directory -Force -Path $sfLogs | Out-Null
New-Item -ItemType File -Force -Path (Join-Path $ProjectDir 'shots/.gdignore') | Out-Null
Write-Output 'Importing resources...'
& $GodotConsole --headless --path $ProjectDir --editor --import --log-file (Join-Path $sfLogs 'import.log') *> (Join-Path $sfLogs 'import-console.log')
if ($LASTEXITCODE -ne 0) { throw 'Godot resource import failed.' }
$sfExe = Join-Path $sfOutput 'SpaceFleet.exe'
Write-Output 'Exporting Windows x64 release...'
& $GodotConsole --headless --path $ProjectDir --export-release 'Windows Desktop' $sfExe --log-file (Join-Path $sfLogs 'export.log') *> (Join-Path $sfLogs 'export-console.log')
if ($LASTEXITCODE -ne 0) { throw 'Godot Windows export failed.' }
if (Select-String -LiteralPath (Join-Path $sfLogs 'export.log') -Pattern 'ERROR:|Exception' -Quiet) { throw 'Export log contains an error.' }

# Runtime/engine licenses accompany the application, including the adapted Carbon code.
Copy-Item -LiteralPath (Join-Path $ProjectDir 'THIRD_PARTY_NOTICES.md') -Destination $sfOutput
$sfCarbon = Join-Path $sfOutput 'third_party/carbon-trinity'
New-Item -ItemType Directory -Force -Path $sfCarbon | Out-Null
foreach ($sfNotice in @('LICENSE.md','NOTICE.md','README.md','sources.json')) {
    Copy-Item -LiteralPath (Join-Path $ProjectDir "third_party/carbon-trinity/$sfNotice") -Destination $sfCarbon
}
Copy-Item -LiteralPath (Join-Path $ProjectDir 'third_party/carbon-trinity/reference') -Destination $sfCarbon -Recurse
$sfLicenses = Join-Path $sfOutput 'licenses'
New-Item -ItemType Directory -Force -Path $sfLicenses | Out-Null
foreach ($sfNotice in @('GODOT-LICENSE.txt','GODOT-COPYRIGHT.txt')) {
    Copy-Item -LiteralPath (Join-Path $ProjectDir ".godot/export-licenses/$sfNotice") -Destination $sfLicenses
}
$sfRuntimeConfig = Get-ChildItem -LiteralPath $sfOutput -Recurse -File -Filter 'SpaceFleet.runtimeconfig.json' | Select-Object -First 1
$sfRuntimeInfo = Get-Content -LiteralPath $sfRuntimeConfig.FullName -Encoding UTF8 -Raw | ConvertFrom-Json
$sfRuntimeVersion = ($sfRuntimeInfo.runtimeOptions.includedFrameworks | Where-Object name -eq 'Microsoft.NETCore.App').version
if (!$sfRuntimeVersion -or !(Get-ChildItem -LiteralPath $sfOutput -Recurse -File -Filter coreclr.dll)) { throw 'Self-contained .NET runtime was not included.' }
$sfRuntimePackage = Join-Path $env:USERPROFILE ".nuget/packages/microsoft.netcore.app.runtime.win-x64/$sfRuntimeVersion"
foreach ($sfNotice in @('LICENSE.TXT','THIRD-PARTY-NOTICES.TXT')) {
    Copy-Item -LiteralPath (Join-Path $sfRuntimePackage $sfNotice) -Destination (Join-Path $sfLicenses "DOTNET-$sfNotice")
}
@'
Space Fleet — Windows x64 개발 빌드

SpaceFleet.exe를 실행하세요. Godot와 .NET을 별도로 설치할 필요가 없습니다.
다른 곳으로 옮길 때는 이 폴더 전체를 복사하세요.
SpaceFleet.pck와 data_* 폴더도 실행에 필요합니다.

시작 → 함선 선택 → 전투. F1: 조작 도움말 / Esc: 일시정지·메뉴.
1 주포 / 2 미사일 / 3 반물질 어뢰(요격함) / 좌클릭 발사 / 우클릭 망원.
F 전력 / B 사격 / N 편대 / 4 드론 방어구역: 누른 채 방향 선택 후 놓기.
M 전장 지도 / F10 효과음 켜기·끄기.

THIRD_PARTY_NOTICES.md, third_party/, licenses/에 사용한 코드와 런타임의 고지가 있습니다.
'@ | Set-Content -LiteralPath (Join-Path $sfOutput '읽어주세요.txt') -Encoding UTF8

# Run from the exported folder: no project path, source assets, or editor executable.
$sfChecks = @()
foreach ($sfTest in @('flow-test','model-test','combat-visual-test','audio-test','fleet-audio-test')) {
    $sfLog = Join-Path $sfLogs "$sfTest.log"
    $sfProcess = Start-Process -FilePath $sfExe -WorkingDirectory $sfOutput -WindowStyle Hidden -PassThru -ArgumentList @('--fixed-fps','60','--log-file',('"'+$sfLog+'"'),'--',"--$sfTest",'--seed=1')
    if (!$sfProcess.WaitForExit(45000)) { Stop-Process -Id $sfProcess.Id; throw "Exported $sfTest timed out." }
    $sfText = Get-Content -LiteralPath $sfLog -Encoding UTF8 -Raw
    if ($sfProcess.ExitCode -ne 0 -or $sfText -match 'ERROR:|Exception' -or $sfText -notmatch 'PASS:') { throw "Exported $sfTest failed: $sfLog" }
    $sfPass = ($sfText -split "`n" | Where-Object { $_ -match 'PASS:' }).Trim()
    $sfChecks += $sfPass
    Write-Output $sfPass
}
$sfInfo = [ordered]@{
    name=$Name; builtAt=[DateTimeOffset]::Now.ToString('o'); engine=(& $GodotConsole --version).Trim()
    sourceCommit=(& git -C $ProjectDir rev-parse HEAD).Trim(); localChanges=[bool](& git -C $ProjectDir status --porcelain)
    platform='Windows x64'; selfContained=$true; checks=$sfChecks
}
$sfInfo | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath (Join-Path $sfOutput 'build-info.json') -Encoding UTF8
Add-Type -AssemblyName System.IO.Compression.FileSystem
$sfArchive = Join-Path $sfRoot "$Name.zip"
[IO.Compression.ZipFile]::CreateFromDirectory($sfOutput,$sfArchive,[IO.Compression.CompressionLevel]::Optimal,$true)
$sfDigest = (Get-FileHash -LiteralPath $sfArchive -Algorithm SHA256).Hash.ToLowerInvariant()
"$sfDigest  $Name.zip" | Set-Content -LiteralPath "$sfArchive.sha256" -Encoding ASCII
Write-Output "Executable: $sfExe"
Write-Output "Archive: $sfArchive"
